from __future__ import annotations

import gc
import json
import os
import shutil
import sys
import threading
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

import numpy as np

from .audio import SAMPLE_RATE, SegmentEvent
from .diarization import DiarizationEngine
from .language import LanguageGuess, MultilingualDetector, normalize_language_code
from .models import Utterance
from .scheduler import GpuResourceManager
from .speaker import OnlineSpeakerClusterer
from .text_normalize import simplify_chinese


OPUS_MT_REPOSITORIES = {
    "en": "Helsinki-NLP/opus-mt-en-zh",
    # The official repository uses an uppercase ZH suffix.
    "de": "Helsinki-NLP/opus-mt-de-ZH",
}

OPUS_MT_TARGET_TAGS = {
    "en": ">>cmn_Hans<<",
    "de": ">>zh_cn<<",
}


def opus_mt_repository(source: str) -> str:
    normalized = normalize_language_code(source) or source
    try:
        return OPUS_MT_REPOSITORIES[normalized]
    except KeyError as exc:
        raise ValueError(f"unsupported OPUS-MT source language: {source}") from exc


def choose_device(requested: str) -> tuple[str, str]:
    requested = (requested or "auto").strip().casefold()
    if requested not in {"auto", "cpu", "cuda"}:
        raise ValueError("MEETING_DEVICE must be auto, cpu or cuda")
    if requested == "cpu":
        return "cpu", "int8"
    try:
        if sys.platform == "win32":
            torch_lib = Path(sys.prefix) / "Lib" / "site-packages" / "torch" / "lib"
            if torch_lib.is_dir():
                os.environ["PATH"] = str(torch_lib) + os.pathsep + os.environ.get("PATH", "")
                if hasattr(os, "add_dll_directory"):
                    os.add_dll_directory(str(torch_lib))
        import ctranslate2

        if ctranslate2.get_cuda_device_count() > 0:
            return "cuda", "int8_float16"
    except Exception:
        pass
    if requested == "cuda":
        raise RuntimeError("CUDA is not available")
    return "cpu", "int8"


@dataclass(slots=True)
class TranslationResult:
    text: str
    status: str
    model: str | None = None
    error: str | None = None


def prepare_opus_mt_model(
    source: str,
    root: Path,
    *,
    progress: Callable[[str], None] | None = None,
) -> Path:
    """Download Marian OPUS-MT and convert it to the local CTranslate2 layout."""
    source = normalize_language_code(source) or source
    target = root / f"{source}-zh"
    target.mkdir(parents=True, exist_ok=True)
    progress = progress or (lambda _message: None)
    from huggingface_hub import snapshot_download

    repository = opus_mt_repository(source)
    progress(f"downloading OPUS-MT {source}->zh")
    # Use the Hub cache instead of ``local_dir``.  On Windows, ``local_dir``
    # may attempt to create symlinks and fail with WinError 1314 when Developer
    # Mode or the SeCreateSymbolicLinkPrivilege is unavailable.
    raw = Path(
        snapshot_download(
            repository,
            allow_patterns=[
                "config.json",
                "generation_config.json",
                "metadata.json",
                "pytorch_model.bin",
                "model.safetensors",
                "source.spm",
                "target.spm",
                "tokenizer_config.json",
                "vocab.json",
                "README.md",
            ],
        )
    )
    progress(f"converting OPUS-MT {source}->zh to CTranslate2")
    from ctranslate2.converters import TransformersConverter
    TransformersConverter(str(raw)).convert(str(target), quantization="int8", force=True)
    for source_path in list(raw.glob("*.spm")) + list(raw.glob("*.model")):
        shutil.copy2(source_path, target / source_path.name)
    raw_config = next((raw / name for name in ("config.json", "model.json") if (raw / name).is_file()), None)
    if raw_config is not None:
        # ``config.json`` generated by CTranslate2 is required at runtime.
        # Keep the original Transformers config under a different name so it
        # cannot overwrite the converted model metadata.
        shutil.copy2(raw_config, target / "source_config.json")
    raw_readme = raw / "README.md"
    if raw_readme.is_file():
        shutil.copy2(raw_readme, target / "source_model_card.md")
    (target / "meeting_model.json").write_text(
        json.dumps({
            "format": "ctranslate2",
            "source": source,
            "target": "zh",
            "target_language_tag": OPUS_MT_TARGET_TAGS[source],
            "repository": repository,
        }, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return target


class RealtimeAsrEngine:
    """Resident realtime ASR engine; deliberately has no fallback route."""

    def __init__(self, model_name: str, gpu_manager: GpuResourceManager, *, autodownload: bool = True) -> None:
        self.model_name = model_name
        self.gpu_manager = gpu_manager
        self.autodownload = autodownload
        self.model: Any | None = None
        self.device = "cpu"
        self.compute_type = "int8"

    def load(self, device: str, compute_type: str) -> Any:
        from faster_whisper import WhisperModel

        self.device = device
        self.compute_type = compute_type
        with self.gpu_manager.acquire_sync("asr_realtime_load"):
            self.model = WhisperModel(
                self.model_name,
                device=device,
                compute_type=compute_type,
                local_files_only=not self.autodownload,
            )
        return self.model

    def release(self) -> None:
        self.model = None


class RefinementAsrEngine:
    """Lazy large-v3 engine loaded only after realtime capture is saved."""

    def __init__(self, model_name: str, gpu_manager: GpuResourceManager, *, autodownload: bool = True) -> None:
        self.model_name = model_name
        self.gpu_manager = gpu_manager
        self.autodownload = autodownload
        self.model: Any | None = None
        self.device = "cpu"
        self.compute_type = "int8"
        self._lock = threading.Lock()

    def ensure_loaded(self, device: str, compute_type: str) -> Any:
        if self.model is not None:
            return self.model
        from faster_whisper import WhisperModel

        with self._lock:
            if self.model is None:
                self.device = device
                self.compute_type = compute_type
                with self.gpu_manager.acquire_sync("asr_refine_load"):
                    self.model = WhisperModel(
                        self.model_name,
                        device=device,
                        compute_type=compute_type,
                        local_files_only=not self.autodownload,
                    )
        return self.model

    def release(self) -> None:
        with self._lock:
            self.model = None


class LiveChineseTranslator:
    """Local OPUS-MT en/de -> zh translator with bounded model discovery."""

    def __init__(self, model_root: Path | None, device: str, progress: Callable[[str], None] | None = None, autodownload: bool = False) -> None:
        self.model_root = model_root
        self.device = device
        self.progress = progress or (lambda _message: None)
        self.autodownload = autodownload
        self.models: dict[str, tuple[Any, Any, Any, str, str]] = {}
        self.failed: dict[str, str] = {}
        self.cache: dict[tuple[str, str], TranslationResult] = {}

    def _find(self, source: str) -> Path | None:
        if not self.model_root:
            return None
        for candidate in (self.model_root / f"{source}-zh", self.model_root / f"{source}_zh", self.model_root / source):
            if (candidate / "model.bin").is_file() and self._spm_paths(candidate) and self._metadata_path(candidate):
                return candidate
        return None

    @staticmethod
    def _metadata_path(path: Path) -> Path | None:
        for name in ("config.json", "model.json", "meeting_model.json", "config.yml", "config.yaml"):
            candidate = path / name
            if candidate.is_file():
                return candidate
        return None

    def _download_if_needed(self, source: str) -> Path | None:
        path = self._find(source)
        if path is not None or not self.autodownload or self.model_root is None:
            return path
        try:
            prepare_opus_mt_model(source, self.model_root, progress=self.progress)
            return self._find(source)
        except Exception as exc:  # pragma: no cover - network/model dependent
            self.failed[source] = str(exc)
            self.progress(f"translation model {source} download failed: {exc}")
            return None

    def assets_snapshot(self) -> dict[str, dict[str, Any]]:
        result: dict[str, dict[str, Any]] = {}
        for source in ("en", "de"):
            path = self._find(source)
            error = self.failed.get(source)
            result[source] = {
                "model": opus_mt_repository(source),
                "path": str(path or (self.model_root / f"{source}-zh" if self.model_root else "")),
                "ready": path is not None,
                "status": "ready" if path is not None else "unsupported" if error == "model not cached" else "failed" if error else "pending",
                "error": error,
            }
        return result

    def preflight(self) -> dict[str, dict[str, Any]]:
        for source in ("en", "de"):
            path = self._download_if_needed(source)
            if path is None:
                self.failed.setdefault(source, "model not cached")
                continue
            if self._spm_paths(path) is None:
                self.failed[source] = "missing SentencePiece model"
        return self.assets_snapshot()

    @staticmethod
    def _spm_paths(path: Path) -> tuple[Path, Path] | None:
        source, target = path / "source.spm", path / "target.spm"
        if source.is_file() and target.is_file():
            return source, target
        for name in ("sentencepiece.bpe.model", "spm.model"):
            candidate = path / name
            if candidate.is_file():
                return candidate, candidate
        matches = list(path.glob("*.spm")) + list(path.glob("*.model"))
        return (matches[0], matches[0]) if matches else None

    def _load(self, source: str) -> tuple[Any, Any, Any, str, str] | None:
        if source in self.models:
            return self.models[source]
        if source in self.failed and self._find(source) is None:
            return None
        self.failed.pop(source, None)
        path = self._download_if_needed(source)
        if path is None:
            self.failed[source] = "model not cached"
            return None
        try:
            import ctranslate2
            import sentencepiece as spm

            paths = self._spm_paths(path)
            if paths is None:
                raise RuntimeError("missing SentencePiece model")
            source_sp = spm.SentencePieceProcessor(model_file=str(paths[0]))
            target_sp = spm.SentencePieceProcessor(model_file=str(paths[1]))
            translator = ctranslate2.Translator(
                str(path),
                device=self.device,
                compute_type="int8_float16" if self.device == "cuda" else "int8",
            )
            metadata_path = path / "meeting_model.json"
            metadata = json.loads(metadata_path.read_text(encoding="utf-8")) if metadata_path.is_file() else {}
            target_tag = str(metadata.get("target_language_tag") or OPUS_MT_TARGET_TAGS.get(source, ""))
            result = (source_sp, target_sp, translator, str(path), target_tag)
            self.models[source] = result
            return result
        except Exception as exc:  # pragma: no cover - optional dependency
            self.failed[source] = str(exc)
            self.progress(f"translation model {source} is unavailable: {exc}")
            return None

    def translate_many(self, texts: list[str], source: str) -> list[TranslationResult]:
        source = normalize_language_code(source) or source
        results: list[TranslationResult | None] = [None] * len(texts)
        pending: list[tuple[int, str]] = []
        for index, text in enumerate(texts):
            value = text.strip()
            if not value:
                results[index] = TranslationResult("", "ready")
            elif source == "zh":
                results[index] = TranslationResult(simplify_chinese(value), "not_needed")
            elif source not in {"en", "de"}:
                results[index] = TranslationResult("", "unsupported", error=f"unsupported source language: {source}")
            elif (source, value) in self.cache:
                results[index] = self.cache[(source, value)]
            else:
                pending.append((index, value))
        loaded = self._load(source) if pending else None
        if loaded is None and pending:
            error = self.failed.get(source, "model unavailable")
            status = "unsupported" if error == "model not cached" else "failed"
            for index, _value in pending:
                results[index] = TranslationResult("", status, error=error)
        elif loaded:
            source_sp, target_sp, translator, model_id, target_tag = loaded
            try:
                # MarianTokenizer appends EOS to every source sequence.  Keep
                # the same input contract when using SentencePiece directly;
                # omitting it causes long/repetitive outputs, especially for
                # the multilingual German->Chinese model.
                pieces = [[target_tag] + source_sp.encode(value, out_type=str) + ["</s>"] for _, value in pending]
                generated = translator.translate_batch(
                    pieces,
                    beam_size=2,
                    max_decoding_length=384,
                    repetition_penalty=1.05,
                )
                for (index, value), hypothesis in zip(pending, generated):
                    tokens = list(hypothesis.hypotheses[0])
                    translated = simplify_chinese(target_sp.decode(tokens).strip())
                    if not translated:
                        results[index] = TranslationResult("", "failed", model_id, "empty translation")
                    else:
                        results[index] = TranslationResult(translated, "ready", model_id)
            except Exception as exc:  # pragma: no cover - optional dependency
                self.progress(f"translation failed: {exc}")
                for index, _value in pending:
                    results[index] = TranslationResult("", "failed", model_id, str(exc))
        final = [item or TranslationResult("", "failed", error="translator returned no result") for item in results]
        for index, value in pending:
            if final[index].status in {"ready", "failed"}:
                self.cache[(source, value)] = final[index]
        return final


# Public architecture name; the old name remains import-compatible.
TranslationEngine = LiveChineseTranslator


@dataclass(slots=True)
class PartialResult:
    revision: int
    start: float
    end: float
    text: str
    language: str | None
    confidence: float = 0.0
    model: str | None = None
    language_source: str = "detector"


class LiveModelRuntime:
    """Model facade used by the session and compatible test runtimes.

    The old constructor is retained for API compatibility.  ``asr_primary``
    now names the single realtime model and ``asr_fallback`` is only an alias
    for integrations that still inspect that field; no hidden fallback model
    is loaded.
    """

    def __init__(
        self,
        asr_primary: str,
        asr_fallback: str,
        asr_refine: str,
        requested_device: str,
        *,
        asr_autodownload: bool = False,
        refinement_enabled: bool = True,
        translation_model_root: Path | None = None,
        translation_autodownload: bool = False,
        vad_model: str = "fsmn-vad",
        gpu_memory_budget_mb: int = 7200,
        diarization_required: bool = True,
    ) -> None:
        self.asr_primary_name = asr_primary or asr_fallback or "large-v3-turbo"
        self.asr_fallback_name = asr_fallback or self.asr_primary_name
        self.asr_refine_name = asr_refine
        self.requested_device = requested_device
        self.asr_autodownload = asr_autodownload
        self.refinement_enabled = refinement_enabled
        self.translation_model_root = translation_model_root
        self.translation_autodownload = translation_autodownload
        self.vad_model_name = vad_model
        self.gpu_memory_budget_mb = gpu_memory_budget_mb
        self.diarization_required = diarization_required
        self.device = "cpu"
        self.compute_type = "int8"
        self.primary: Any | None = None
        self.fallback: Any | None = None
        self.refine: Any | None = None
        self.translator: LiveChineseTranslator | None = None
        self.detector = MultilingualDetector()
        self.speaker_encoder = None
        self.vad: Any | None = None
        self.diarization = DiarizationEngine(
            "cpu",
            required=diarization_required,
        )
        self.gpu_manager = GpuResourceManager()
        self.realtime_engine = RealtimeAsrEngine(
            self.asr_primary_name,
            self.gpu_manager,
            autodownload=asr_autodownload,
        )
        self.refinement_engine = RefinementAsrEngine(
            self.asr_refine_name,
            self.gpu_manager,
            autodownload=asr_autodownload,
        )
        self.ready = False
        self.capabilities_ready = False
        self.status = "waiting for model load"
        self.metrics: dict[str, Any] = {
            "asr_calls": 0,
            "translation_calls": 0,
            "model_events": [],
            "oom_count": 0,
            "fallback_count": 0,
            "stage_failures": 0,
            "retry_count": 0,
            "queue_lengths": {},
        }
        self._refine_lock = threading.Lock()
        self.asr_cache_ready = True
        self.last_asr_error: str | None = None
        self.last_asr_error_model: str | None = None

    def _event(self, name: str, **details: Any) -> None:
        events = self.metrics.setdefault("model_events", [])
        if isinstance(events, list):
            events.append({"event": name, **details})
            del events[:-50]

    @staticmethod
    def _whisper_repo(model_name: str) -> str | None:
        name = str(model_name or "")
        if name in {"large-v3", "openai/whisper-large-v3"}:
            return "Systran/faster-whisper-large-v3"
        if name in {"large-v3-turbo", "openai/whisper-large-v3-turbo"}:
            return "mobiuslabsgmbh/faster-whisper-large-v3-turbo"
        return None

    def _prepare_asr_cache(self, model_name: str, progress: Callable[[str], None]) -> bool:
        repo = self._whisper_repo(model_name)
        if repo is None:
            return True
        try:
            from faster_whisper.utils import download_model

            progress(f"Checking ASR model cache: {model_name}")
            download_model(repo, local_files_only=not self.asr_autodownload)
            return True
        except Exception as exc:
            self._event("asr_preflight_error", model=model_name, error=str(exc))
            return False

    def _resolve_vad_source(self) -> str:
        """Resolve a cached VAD model to a local snapshot path.

        FunASR accepts either a model id or a local model directory. Passing
        the local snapshot avoids a Hugging Face metadata request on every
        server start after the deployment bundle has been prepared.
        """
        configured = str(self.vad_model_name or "").strip()
        if configured in {"", "disabled"} or Path(configured).exists():
            return configured
        if configured != "fsmn-vad":
            return configured
        try:
            from huggingface_hub import snapshot_download

            return str(snapshot_download(
                repo_id="funasr/fsmn-vad",
                local_files_only=True,
            ))
        except Exception:
            if not self.asr_autodownload:
                raise RuntimeError(
                    "VAD model fsmn-vad is not present in the local Hugging Face cache; "
                    "run scripts/prepare_models.py on the build host or enable download "
                    "only during model preparation"
                )
            return configured

    def load(self, progress: Callable[[str], None] | None = None) -> None:
        progress = progress or (lambda _message: None)
        self.device, self.compute_type = choose_device(self.requested_device)
        try:
            progress(f"Loading realtime ASR: {self.asr_primary_name}")
            self.primary = self.realtime_engine.load(self.device, self.compute_type)
            self.fallback = self.primary  # backwards-compatible alias only
            self.asr_cache_ready = self._prepare_asr_cache(self.asr_refine_name, progress)
            if self.refinement_enabled and self.asr_refine_name and self.asr_refine_name != self.asr_primary_name:
                progress(f"Refinement model will load on demand: {self.asr_refine_name}")
            self.translator = LiveChineseTranslator(
                self.translation_model_root,
                self.device,
                progress,
                self.translation_autodownload,
            )
            translation_assets = self.translator.preflight()
            try:
                from funasr import AutoModel

                runtime_device = f"{self.device}:0" if self.device == "cuda" else self.device
                self.vad = AutoModel(
                    model=self._resolve_vad_source(),
                    hub="hf",
                    trust_remote_code=True,
                    disable_update=True,
                    device=runtime_device,
                )
            except Exception:
                self.vad = None
            self.ready = True
            self.diarization.device = self.device
            diarization_ready = self.diarization.preflight()
            self.capabilities_ready = (
                all(item["ready"] for item in translation_assets.values())
                and (not self.diarization_required or diarization_ready)
                and self.vad is not None
                and self.asr_cache_ready
            )
            issues = self._capability_issues()
            self.status = "models ready" if not issues else "ASR ready; missing capabilities: " + "; ".join(issues)
            self._event("ready", device=self.device, capabilities_ready=self.capabilities_ready)
            progress(self.status)
        except Exception as exc:
            self.ready = False
            self.capabilities_ready = False
            self.status = f"model load failed: {exc}"
            self._event("load_error", error=str(exc))
            progress(self.status)

    def close(self) -> None:
        self.realtime_engine.release()
        self.refinement_engine.release()
        self.primary = self.fallback = self.refine = self.translator = self.vad = None
        self.diarization.close()
        self.ready = False
        self.capabilities_ready = False
        gc.collect()
        self.status = "models released"

    def release_realtime_model(self) -> None:
        """Release the resident realtime ASR before GPU-heavy postprocess."""
        self.primary = None
        self.fallback = None
        self.realtime_engine.release()
        self.ready = False
        self.capabilities_ready = False
        self.status = "realtime model released; waiting for warmup"
        self._event("realtime_released", model=self.asr_primary_name)
        gc.collect()

    def warm_realtime(self, progress: Callable[[str], None] | None = None) -> None:
        if self.primary is not None:
            self.ready = True
            self.capabilities_ready = self._capabilities_ready()
            return
        progress = progress or (lambda _message: None)
        try:
            progress(f"warming realtime ASR: {self.asr_primary_name}")
            self.primary = self.realtime_engine.load(self.device, self.compute_type)
            self.fallback = self.primary
            self.ready = True
            self.capabilities_ready = self._capabilities_ready()
            issues = self._capability_issues()
            self.status = "models ready" if not issues else "realtime ASR ready; missing capabilities: " + "; ".join(issues)
            self._event("realtime_warmed", model=self.asr_primary_name)
        except Exception as exc:
            self.ready = False
            self.capabilities_ready = False
            self.status = f"realtime warmup failed: {exc}"
            self._event("realtime_warmup_error", model=self.asr_primary_name, error=str(exc))

    def _capabilities_ready(self) -> bool:
        translation_ready = self.translator is not None and all(
            item["ready"] for item in self.translator.assets_snapshot().values()
        )
        return bool(
            translation_ready
            and (not self.diarization_required or self.diarization.capability_ready())
            and (self.vad is not None or self.vad_model_name == "disabled")
            and self.asr_cache_ready
        )

    def _capability_issues(self) -> list[str]:
        issues: list[str] = []
        if self.refinement_enabled and not self.asr_cache_ready:
            issues.append(f"ASR refine unavailable: {self.asr_refine_name}")
        translation = self.translator.assets_snapshot() if self.translator is not None else {}
        for source in ("en", "de"):
            asset = translation.get(source, {})
            if not asset.get("ready"):
                issues.append(f"translation {source}->zh {asset.get('status', 'missing')}")
        if self.vad_model_name != "disabled" and self.vad is None:
            issues.append(f"VAD unavailable: {self.vad_model_name}")
        if self.diarization_required and not self.diarization.capability_ready():
            issues.append(f"diarization unavailable: {self.diarization.error or self.diarization.model_name}")
        return issues

    def release_postprocess_models(self) -> None:
        self.refinement_engine.release()
        self.refine = None
        self.diarization.close()
        self._event("postprocess_released", model=self.asr_refine_name)
        gc.collect()

    def new_speaker_clusterer(self) -> OnlineSpeakerClusterer:
        return OnlineSpeakerClusterer(self.device, encoder=self.speaker_encoder)

    def new_vad(self) -> Callable[[bytes], bool | None] | None:
        if self.vad is None:
            return None
        cache: dict[str, Any] = {}

        def decide(frame: bytes) -> bool | None:
            audio = np.frombuffer(frame, dtype=np.int16).astype(np.float32) / 32768.0
            try:
                result = self.vad.generate(input=audio, cache=cache, is_final=False)
                payload = result[0] if isinstance(result, list) and result else result
                if isinstance(payload, dict):
                    for key in ("is_speech", "speech", "speech_prob", "score"):
                        if key in payload:
                            value = payload[key]
                            return bool(value) if key == "is_speech" else float(value) > 0.5
            except Exception:
                return None
            return None

        return decide

    @staticmethod
    def _audio(pcm: bytes) -> np.ndarray:
        return np.frombuffer(pcm, dtype=np.int16).astype(np.float32) / 32768.0

    def _whisper(self, pcm: bytes, model: Any, *, refine: bool = False) -> tuple[str, str | None, float]:
        if model is None:
            return "", None, 0.0
        segments, info = model.transcribe(
            self._audio(pcm),
            beam_size=5 if refine else 1,
            vad_filter=False,
            condition_on_previous_text=False,
        )
        text = " ".join(segment.text.strip() for segment in segments if segment.text.strip()).strip()
        language = getattr(info, "language", None)
        probability = float(getattr(info, "language_probability", 0.0) or 0.0)
        return text, language, probability

    def _recognize(self, pcm: bytes, *, refine: bool = False) -> tuple[str, LanguageGuess, float, str, str]:
        self.last_asr_error = None
        self.last_asr_error_model = self.asr_refine_name if refine else self.asr_primary_name
        model = self._ensure_refine_model() if refine else self.primary
        model_name = self.asr_refine_name if refine else self.asr_primary_name
        if model is None or not hasattr(model, "transcribe"):
            return "", LanguageGuess("zh", 0.0), 0.0, "none", "detector"
        try:
            if self.device == "cuda":
                with self.gpu_manager.acquire_sync("asr_refine" if refine else "asr_realtime"):
                    text, language, confidence = self._whisper(pcm, model, refine=refine)
            else:
                text, language, confidence = self._whisper(pcm, model, refine=refine)
            guess = self.detector.detect(text, whisper_language=language, whisper_confidence=confidence)
            self.metrics["asr_calls"] = int(self.metrics.get("asr_calls", 0)) + 1
            return text, guess, confidence, model_name, "asr" if language else "detector"
        except Exception as exc:
            self.metrics["stage_failures"] = int(self.metrics.get("stage_failures", 0)) + 1
            self._event("asr_error", model=model_name, refine=refine, error=str(exc))
            self.last_asr_error = str(exc)
            self.last_asr_error_model = model_name
            return "", LanguageGuess("zh", 0.0), 0.0, model_name, "detector"

    def _ensure_refine_model(self) -> Any | None:
        if not self.refinement_enabled or not self.asr_refine_name:
            return None
        if not self.asr_cache_ready:
            raise RuntimeError(f"ASR refinement model cache is not ready: {self.asr_refine_name}")
        if self.refine is not None:
            return self.refine
        with self._refine_lock:
            if self.refine is not None:
                return self.refine
            try:
                self.refine = self.refinement_engine.ensure_loaded(self.device, self.compute_type)
                self._event("refine_loaded", model=self.asr_refine_name, device=self.device)
            except Exception as exc:
                self.metrics["stage_failures"] = int(self.metrics.get("stage_failures", 0)) + 1
                self._event("refine_error", model=self.asr_refine_name, error=str(exc))
                self.last_asr_error = str(exc)
                self.last_asr_error_model = self.asr_refine_name
                self.refine = None
            return self.refine

    def transcribe_partial(self, event: SegmentEvent, recent_text: str = "", hotwords: str | None = None) -> PartialResult:
        text, guess, confidence, model, language_source = self._recognize(event.pcm)
        return PartialResult(event.revision, event.start, event.end, text, guess.code if text else None, confidence, model, language_source)

    def transcribe_draft(self, event: SegmentEvent, recent_text: str = "", hotwords: str | None = None) -> PartialResult:
        return self.transcribe_partial(event, recent_text, hotwords)

    def transcribe_final(
        self,
        event: SegmentEvent,
        *,
        next_id: int,
        previous_language: str | None = None,
        recent_text: str = "",
        hotwords: str | None = None,
        speaker_clusterer: OnlineSpeakerClusterer | None = None,
        refined: bool = True,
    ) -> list[Utterance]:
        text, whisper_guess, confidence, model, language_source = self._recognize(event.pcm, refine=refined)
        if not text:
            if refined and self.last_asr_error:
                raise RuntimeError(
                    f"ASR refinement failed ({self.last_asr_error_model or self.asr_refine_name}): {self.last_asr_error}"
                )
            return []
        guess = self.detector.detect(
            text,
            previous=previous_language,
            whisper_language=whisper_guess.code,
            whisper_confidence=confidence,
        )
        speaker = speaker_clusterer.assign(event.pcm, event.end - event.start) if speaker_clusterer else 1
        pieces = self.detector.split_clauses(text)
        result: list[Utterance] = []
        total = max(1, len(pieces))
        cursor = event.start
        for index, piece in enumerate(pieces):
            duration = max(0.05, (event.end - event.start) / total)
            end = min(event.end, cursor + duration)
            segment_id = f"{event.revision}:{index}"
            source_segment_id = str(event.revision)
            value = simplify_chinese(piece) if guess.code == "zh" else piece
            result.append(Utterance(
                next_id + index,
                cursor,
                end,
                speaker,
                guess.code,
                max(confidence, guess.confidence),
                value,
                value if guess.code == "zh" else "",
                "not_needed" if guess.code == "zh" else "pending",
                segment_id,
                2 if refined else 1,
                "refined" if refined else "fast",
                source_segment_id,
                model,
                language_source,
                "online",
                0.0,
                [speaker],
            ))
            cursor = end
        return result

    def transcribe_refined(self, event: SegmentEvent, **kwargs: Any) -> list[Utterance]:
        kwargs["refined"] = True
        return self.transcribe_final(event, **kwargs)

    def translate_text(self, text: str, source_language: str) -> TranslationResult:
        if self.translator is None:
            return TranslationResult("", "unsupported", error="translator is not ready")
        self.metrics["translation_calls"] = int(self.metrics.get("translation_calls", 0)) + 1
        if self.device == "cuda":
            with self.gpu_manager.acquire_sync("translation"):
                return self.translator.translate_many([text], source_language)[0]
        return self.translator.translate_many([text], source_language)[0]

    def translate_text_batch(self, texts: list[str], source_language: str) -> list[TranslationResult]:
        if self.translator is None:
            return [TranslationResult("", "unsupported", error="translator is not ready") for _ in texts]
        self.metrics["translation_calls"] = int(self.metrics.get("translation_calls", 0)) + len(texts)
        if self.device == "cuda":
            with self.gpu_manager.acquire_sync("translation"):
                return self.translator.translate_many(texts, source_language)
        return self.translator.translate_many(texts, source_language)

    def diarize_audio(self, audio_paths: list[Path]) -> list[Any]:
        if self.device == "cuda":
            with self.gpu_manager.acquire_sync("diarization"):
                result = self.diarization.diarize(audio_paths)
        else:
            result = self.diarization.diarize(audio_paths)
        return result

    def capability_snapshot(self) -> dict[str, Any]:
        translation = self.translator.assets_snapshot() if self.translator is not None else {
            "en": {"model": "Helsinki-NLP/opus-mt-en-zh", "ready": False},
            "de": {"model": opus_mt_repository("de"), "ready": False},
        }
        return {
            "asr_realtime": {"model": self.asr_primary_name, "ready": self.primary is not None, "fallback": None},
            "asr_refine": {"model": self.asr_refine_name, "ready": self.refine is not None, "cache_ready": self.asr_cache_ready, "load_policy": "on_demand"},
            "translation": {"models": translation, "ready": all(item["ready"] for item in translation.values())},
            "vad": {"model": self.vad_model_name, "ready": self.vad is not None},
            "diarization": {
                "model": self.diarization.model_name,
                "backend": self.diarization.backend,
                "ready": self.diarization.ready or self.diarization.capability_ready(),
                "available": self.diarization.capability_ready(),
                "status": self.diarization.status,
                "weights_ready": self.diarization.model_size_bytes is not None,
                "weight_bytes": self.diarization.model_size_bytes,
                "parameters": self.diarization.model_parameters(),
                "error": self.diarization.error,
            },
        }
